In [ ]:
# Install Yahoo finance python package
# pip install yfinance
# Library imports
import yfinance as yf
import pandas as pd
sp = yf.download("^GSPC", start="2025-07-30", end = "2026-03-11")
# Data frame comes in Wide form, drop ticker header (all SP500)
sp.columns = sp.columns.droplevel(1)
#fix index
sp = sp.reset_index()
#fix names
sp.columns.name = None
#set index to date time for joining on date
sp['Date'] = pd.to_datetime(sp['Date'])
sp = sp.set_index('Date')
sp.head()

[*********************100%***********************]  1 of 1 completed

                  Close         High          Low         Open      Volume
Date
2025-07-30  6362.899902  6396.540039  6336.379883  6381.229980  5375070000
2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000
2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000
2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000
2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000

In [10]:
# Create day change percentage column to find volatile days for volatity clustering.
sp['Day Change %'] = (sp['Close'] - sp['Open']) / sp['Open'] * 100
sp.head()

,Close,High,Low,Open,Volume,Day Change %
Date,,,,,,
2025-07-30,6362.899902,6396.540039,6336.379883,6381.229980,5375070000,-0.287250
2025-07-31,6339.390137,6427.020020,6327.640137,6427.020020,6077080000,-1.363461
2025-08-01,6238.009766,6287.279785,6212.689941,6287.279785,5827150000,-0.783646
2025-08-04,6329.939941,6330.689941,6271.709961,6271.709961,4842580000,0.928455
2025-08-05,6299.189941,6346.000000,6289.370117,6336.629883,5517410000,-0.590849

In [ ]:
#Save to csv for use in notebook
#sp.to_csv('SP500_data.csv')
#Save to parquet for use in notebook and maintain data types
sp.to_parquet('SP500_data.parquet')