<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [2]</a>'.</span>

In [111]:
import pandas as pd
from datetime import datetime, timezone


import papermill as pm

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [112]:
pm.execute_notebook('data_consolidation.ipynb', 'data_consolidation.ipynb')

Executing:   0%|          | 0/23 [00:00<?, ?cell/s]

{'cells': [{'cell_type': 'code',
   'execution_count': 1,
   'id': '908b51fe',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:31.372850Z',
     'iopub.execute_input': '2026-03-12T23:41:31.373052Z',
     'iopub.status.idle': '2026-03-12T23:41:32.534128Z',
     'shell.execute_reply': '2026-03-12T23:41:32.533849Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:31.367861+00:00',
     'end_time': '2026-03-12T23:41:32.536076+00:00',
     'duration': 1.168215,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "# Imports\nimport pandas as pd\nimport papermill as pm #papermill allows us to execute notebooks not just .py files.\nimport sys\nimport os\nsys.path.append(os.path.abspath('..')) \nfrom data_collection import fred_data_download as fred_data_download"},
  {'cell_type': 'code',
   'execution_count': 2,
   'id': '79aba66c',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:32.547957Z',
     'iopub.execute_input': '2026-03-12T23:41:32.548242Z',
     'iopub.status.idle': '2026-03-12T23:41:38.699803Z',
     'shell.execute_reply': '2026-03-12T23:41:38.699308Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:32.544918+00:00',
     'end_time': '2026-03-12T23:41:38.701298+00:00',
     'duration': 6.15638,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'display_data',
     'metadata': {},
     'data': {'text/plain': 'Executing:   0%|          | 0/4 [00:00<?, ?cell/s]',
      'application/vnd.jupyter.widget-view+json': {'version_major': 2,
       'version_minor': 0,
       'model_id': '426635081f894728ab50a796090db749'}}},
    {'output_type': 'display_data',
     'metadata': {},
     'data': {'text/plain': 'Executing:   0%|          | 0/1 [00:00<?, ?cell/s]',
      'application/vnd.jupyter.widget-view+json': {'version_major': 2,
       'version_minor': 0,
       'model_id': 'd81463e40c664648bde5ef6ab54f44c8'}}},
    {'output_type': 'stream',
     'name': 'stdout',
     'text': '            3m_treasury  2yr_treasury  10yr_treasury  yield_curve    VIX  \\\ndate                                                                       \n2025-07-30         4.41          3.94           4.38         0.44  15.48   \n2025-07-31         4.41          3.94           4.37         0.43  16.72   \n2025-08-01         4.35          3.69           4.23         0.54  20.38   \n2025-08-02          NaN           NaN            NaN          NaN    NaN   \n2025-08-03          NaN           NaN            NaN          NaN    NaN   \n\n            fed_funds_rate  \ndate                        \n2025-07-30            4.33  \n2025-07-31            4.33  \n2025-08-01            4.33  \n2025-08-02            4.33  \n2025-08-03            4.33  \n'}],
   'source': "#Execute child notebooks\npm.execute_notebook('SP500_notebook.ipynb', 'SP500_notebook.ipynb')\npm.execute_notebook('SP500futures_notebook.ipynb', 'SP500futures_notebook.ipynb')\nfred_data_download.run_fred_download()\n"},
  {'cell_type': 'code',
   'execution_count': 3,
   'id': 'e550a085',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.711476Z',
     'iopub.execute_input': '2026-03-12T23:41:38.711752Z',
     'iopub.status.idle': '2026-03-12T23:41:38.813263Z',
     'shell.execute_reply': '2026-03-12T23:41:38.811948Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.707011+00:00',
     'end_time': '2026-03-12T23:41:38.816188+00:00',
     'duration': 0.109177,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "# Pull DFS\nsp = pd.read_parquet('../data/SP500_data.parquet')\nfred = pd.read_parquet('../data/fred_data.parquet')\nfutures = pd.read_csv('../data/Overnight_SP500_data.csv')"},
  {'cell_type': 'code',
   'execution_count': 4,
   'id': '674a6ee8',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.827084Z',
     'iopub.execute_input': '2026-03-12T23:41:38.827712Z',
     'iopub.status.idle': '2026-03-12T23:41:38.837547Z',
     'shell.execute_reply': '2026-03-12T23:41:38.837042Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.820594+00:00',
     'end_time': '2026-03-12T23:41:38.838677+00:00',
     'duration': 0.018083,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 226 entries, 2025-07-30 to 2026-03-12\nData columns (total 6 columns):\n #   Column          Non-Null Count  Dtype  \n---  ------          --------------  -----  \n 0   3m_treasury     153 non-null    float64\n 1   2yr_treasury    153 non-null    float64\n 2   10yr_treasury   153 non-null    float64\n 3   yield_curve     154 non-null    float64\n 4   VIX             159 non-null    float64\n 5   fed_funds_rate  225 non-null    float64\ndtypes: float64(6)\nmemory usage: 12.4 KB\n"}],
   'source': 'fred.info()'},
  {'cell_type': 'code',
   'execution_count': 5,
   'id': '289d6a4c',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.847413Z',
     'iopub.execute_input': '2026-03-12T23:41:38.847574Z',
     'iopub.status.idle': '2026-03-12T23:41:38.852193Z',
     'shell.execute_reply': '2026-03-12T23:41:38.851926Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.843537+00:00',
     'end_time': '2026-03-12T23:41:38.852975+00:00',
     'duration': 0.009438,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 153 entries, 2025-07-31 to 2026-03-10\nData columns (total 7 columns):\n #   Column              Non-Null Count  Dtype  \n---  ------              --------------  -----  \n 0   Close               153 non-null    float64\n 1   High                153 non-null    float64\n 2   Low                 153 non-null    float64\n 3   Open                153 non-null    float64\n 4   Volume              153 non-null    int64  \n 5   Day Change %        153 non-null    float64\n 6   Overnight Change %  153 non-null    float64\ndtypes: float64(6), int64(1)\nmemory usage: 9.6 KB\n"}],
   'source': 'sp.info()'},
  {'cell_type': 'code',
   'execution_count': 6,
   'id': 'c685226a',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.860731Z',
     'iopub.execute_input': '2026-03-12T23:41:38.860901Z',
     'iopub.status.idle': '2026-03-12T23:41:38.864052Z',
     'shell.execute_reply': '2026-03-12T23:41:38.863018Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.856310+00:00',
     'end_time': '2026-03-12T23:41:38.865627+00:00',
     'duration': 0.009317,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "fred.index.name = 'Date'"},
  {'cell_type': 'code',
   'execution_count': 7,
   'id': '8629418f',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.874965Z',
     'iopub.execute_input': '2026-03-12T23:41:38.875116Z',
     'iopub.status.idle': '2026-03-12T23:41:38.880278Z',
     'shell.execute_reply': '2026-03-12T23:41:38.879320Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.870468+00:00',
     'end_time': '2026-03-12T23:41:38.881269+00:00',
     'duration': 0.010801,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "#Perform Left join on date to consolidate dataframes for modeling.\ndata = pd.merge(sp, fred, on='Date', how='left')"},
  {'cell_type': 'code',
   'execution_count': 8,
   'id': '4da00558',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.887916Z',
     'iopub.execute_input': '2026-03-12T23:41:38.888110Z',
     'iopub.status.idle': '2026-03-12T23:41:38.894717Z',
     'shell.execute_reply': '2026-03-12T23:41:38.894149Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.884127+00:00',
     'end_time': '2026-03-12T23:41:38.895817+00:00',
     'duration': 0.01169,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'execute_result',
     'metadata': {},
     'data': {'text/plain': '                  Close         High          Low         Open      Volume  \\\nDate                                                                         \n2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000   \n2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000   \n2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000   \n2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000   \n2025-08-06  6345.060059  6352.830078  6301.109863  6309.299805  5408560000   \n\n            Day Change %  Overnight Change %  3m_treasury  2yr_treasury  \\\nDate                                                                      \n2025-07-31     -1.363461            1.007718         4.41          3.94   \n2025-08-01     -0.783646           -0.822009         4.35          3.69   \n2025-08-04      0.928455            0.540240         4.35          3.69   \n2025-08-05     -0.590849            0.105687         4.34          3.72   \n2025-08-06      0.566786            0.160495         4.32          3.69   \n\n            10yr_treasury  yield_curve    VIX  fed_funds_rate  \nDate                                                           \n2025-07-31           4.37         0.43  16.72            4.33  \n2025-08-01           4.23         0.54  20.38            4.33  \n2025-08-04           4.22         0.53  17.52            4.33  \n2025-08-05           4.22         0.50  17.85            4.33  \n2025-08-06           4.22         0.53  16.77            4.33  ',
      'text/html': '<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Close</th>\n      <th>High</th>\n      <th>Low</th>\n      <th>Open</th>\n      <th>Volume</th>\n      <th>Day Change %</th>\n      <th>Overnight Change %</th>\n      <th>3m_treasury</th>\n      <th>2yr_treasury</th>\n      <th>10yr_treasury</th>\n      <th>yield_curve</th>\n      <th>VIX</th>\n      <th>fed_funds_rate</th>\n    </tr>\n    <tr>\n      <th>Date</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2025-07-31</th>\n      <td>6339.390137</td>\n      <td>6427.020020</td>\n      <td>6327.640137</td>\n      <td>6427.020020</td>\n      <td>6077080000</td>\n      <td>-1.363461</td>\n      <td>1.007718</td>\n      <td>4.41</td>\n      <td>3.94</td>\n      <td>4.37</td>\n      <td>0.43</td>\n      <td>16.72</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-01</th>\n      <td>6238.009766</td>\n      <td>6287.279785</td>\n      <td>6212.689941</td>\n      <td>6287.279785</td>\n      <td>5827150000</td>\n      <td>-0.783646</td>\n      <td>-0.822009</td>\n      <td>4.35</td>\n      <td>3.69</td>\n      <td>4.23</td>\n      <td>0.54</td>\n      <td>20.38</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-04</th>\n      <td>6329.939941</td>\n      <td>6330.689941</td>\n      <td>6271.709961</td>\n      <td>6271.709961</td>\n      <td>4842580000</td>\n      <td>0.928455</td>\n      <td>0.540240</td>\n      <td>4.35</td>\n      <td>3.69</td>\n      <td>4.22</td>\n      <td>0.53</td>\n      <td>17.52</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-05</th>\n      <td>6299.189941</td>\n      <td>6346.000000</td>\n      <td>6289.370117</td>\n      <td>6336.629883</td>\n      <td>5517410000</td>\n      <td>-0.590849</td>\n      <td>0.105687</td>\n      <td>4.34</td>\n      <td>3.72</td>\n      <td>4.22</td>\n      <td>0.50</td>\n      <td>17.85</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-06</th>\n      <td>6345.060059</td>\n      <td>6352.830078</td>\n      <td>6301.109863</td>\n      <td>6309.299805</td>\n      <td>5408560000</td>\n      <td>0.566786</td>\n      <td>0.160495</td>\n      <td>4.32</td>\n      <td>3.69</td>\n      <td>4.22</td>\n      <td>0.53</td>\n      <td>16.77</td>\n      <td>4.33</td>\n    </tr>\n  </tbody>\n</table>\n</div>'},
     'execution_count': 8}],
   'source': 'data.head()'},
  {'cell_type': 'code',
   'execution_count': 9,
   'id': 'edf2eae5',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.905419Z',
     'iopub.execute_input': '2026-03-12T23:41:38.905623Z',
     'iopub.status.idle': '2026-03-12T23:41:38.909185Z',
     'shell.execute_reply': '2026-03-12T23:41:38.908906Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.902660+00:00',
     'end_time': '2026-03-12T23:41:38.909841+00:00',
     'duration': 0.007181,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 153 entries, 2025-07-31 to 2026-03-10\nData columns (total 13 columns):\n #   Column              Non-Null Count  Dtype  \n---  ------              --------------  -----  \n 0   Close               153 non-null    float64\n 1   High                153 non-null    float64\n 2   Low                 153 non-null    float64\n 3   Open                153 non-null    float64\n 4   Volume              153 non-null    int64  \n 5   Day Change %        153 non-null    float64\n 6   Overnight Change %  153 non-null    float64\n 7   3m_treasury         151 non-null    float64\n 8   2yr_treasury        151 non-null    float64\n 9   10yr_treasury       151 non-null    float64\n 10  yield_curve         151 non-null    float64\n 11  VIX                 153 non-null    float64\n 12  fed_funds_rate      153 non-null    float64\ndtypes: float64(12), int64(1)\nmemory usage: 16.7 KB\n"}],
   'source': 'data.info()'},
  {'cell_type': 'code',
   'execution_count': 10,
   'id': 'fb241f1b',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.915510Z',
     'iopub.execute_input': '2026-03-12T23:41:38.915643Z',
     'iopub.status.idle': '2026-03-12T23:41:38.918006Z',
     'shell.execute_reply': '2026-03-12T23:41:38.917757Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.912382+00:00',
     'end_time': '2026-03-12T23:41:38.918678+00:00',
     'duration': 0.006296,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stderr',
     'text': "/var/folders/3n/hh67zc0j3vl1gh8dpln88fv40000gn/T/ipykernel_35010/1399603370.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n  data = data.fillna(method='ffill')\n"}],
   'source': "#show null rows\ndata[data.isnull().any(axis=1)]\n#nulls in 3m_treasury, 2 yr 10 yr, vix ,fed funds, solve with ffill\ndata = data.fillna(method='ffill')"},
  {'cell_type': 'code',
   'execution_count': 11,
   'id': '1d59cf39',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.927072Z',
     'iopub.execute_input': '2026-03-12T23:41:38.927232Z',
     'shell.execute_reply': '2026-03-12T23:41:38.930539Z',
     'iopub.status.idle': '2026-03-12T23:41:38.930817Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.922302+00:00',
     'end_time': '2026-03-12T23:41:38.931546+00:00',
     'duration': 0.009244,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 153 entries, 2025-07-31 to 2026-03-10\nData columns (total 13 columns):\n #   Column              Non-Null Count  Dtype  \n---  ------              --------------  -----  \n 0   Close               153 non-null    float64\n 1   High                153 non-null    float64\n 2   Low                 153 non-null    float64\n 3   Open                153 non-null    float64\n 4   Volume              153 non-null    int64  \n 5   Day Change %        153 non-null    float64\n 6   Overnight Change %  153 non-null    float64\n 7   3m_treasury         153 non-null    float64\n 8   2yr_treasury        153 non-null    float64\n 9   10yr_treasury       153 non-null    float64\n 10  yield_curve         153 non-null    float64\n 11  VIX                 153 non-null    float64\n 12  fed_funds_rate      153 non-null    float64\ndtypes: float64(12), int64(1)\nmemory usage: 16.7 KB\n"}],
   'source': 'data.info()'},
  {'cell_type': 'code',
   'execution_count': 12,
   'id': 'f0b749d5',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.936375Z',
     'iopub.execute_input': '2026-03-12T23:41:38.936479Z',
     'iopub.status.idle': '2026-03-12T23:41:38.939265Z',
     'shell.execute_reply': '2026-03-12T23:41:38.939025Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.933966+00:00',
     'end_time': '2026-03-12T23:41:38.939895+00:00',
     'duration': 0.005929,
     'status': 'completed'},
    'tags': []},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 186 entries, 0 to 185\nData columns (total 4 columns):\n #   Column                Non-Null Count  Dtype  \n---  ------                --------------  -----  \n 0   Date                  186 non-null    object \n 1   Overnight_Return      186 non-null    float64\n 2   Overnight_Volatility  186 non-null    float64\n 3   Futures_Last_Price    186 non-null    float64\ndtypes: float64(3), object(1)\nmemory usage: 5.9+ KB\n"}],
   'source': 'futures.info()\n'},
  {'cell_type': 'code',
   'execution_count': 13,
   'id': '5e21c4db',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.945336Z',
     'iopub.execute_input': '2026-03-12T23:41:38.945443Z',
     'iopub.status.idle': '2026-03-12T23:41:38.948069Z',
     'shell.execute_reply': '2026-03-12T23:41:38.947775Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.942199+00:00',
     'end_time': '2026-03-12T23:41:38.948708+00:00',
     'duration': 0.006509,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "#convert futures to date time index\nfutures['Date'] = pd.to_datetime(futures['Date'])\nfutures.index = futures['Date']\nfutures = futures.drop(columns=['Date'])"},
  {'cell_type': 'code',
   'execution_count': 14,
   'id': 'ee4ed504',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.953545Z',
     'iopub.execute_input': '2026-03-12T23:41:38.953719Z',
     'iopub.status.idle': '2026-03-12T23:41:38.956198Z',
     'shell.execute_reply': '2026-03-12T23:41:38.955969Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.951121+00:00',
     'end_time': '2026-03-12T23:41:38.956808+00:00',
     'duration': 0.005687,
     'status': 'completed'},
    'tags': []},
   'outputs': [],
   'source': "#Merge with consolidated data\ndata = pd.merge(data, futures, on='Date', how='left')"},
  {'cell_type': 'code',
   'execution_count': 15,
   'id': 'b98b7f65',
   'metadata': {'execution': {'iopub.status.busy': '2026-03-12T23:41:38.961619Z',
     'iopub.execute_input': '2026-03-12T23:41:38.961725Z',
     'iopub.status.idle': '2026-03-12T23:41:38.964901Z',
     'shell.execute_reply': '2026-03-12T23:41:38.964680Z'},
    'papermill': {'exception': False,
     'start_time': '2026-03-12T23:41:38.959116+00:00',
     'end_time': '2026-03-12T23:41:38.965543+00:00',
     'duration': 0.006427,

In [113]:
### Execute api pulls
pm.execute_notebook('pull_api.ipynb', 'pull_api_output.ipynb')

### Read in data

#load in kalshi ticker data
kalshi_df = pd.read_csv("../data/kalshi_full_data.csv")

#load in kalshi markets data to get open and close times for filtering
markets_df = pd.read_csv("../data/kalshi_markets.csv")

#select columns with open and close times
markets_df_cols = markets_df[["close_time", "open_time", "ticker"]]

Executing:   0%|          | 0/3 [00:00<?, ?cell/s]

In [114]:
### Manipulate datetime to get closest ticker to timestamp (eliminate bets for future fed decisions)

# extract ticker suffix to indicate which bet is being made
kalshi_df['ticker_suffix'] = kalshi_df['ticker'].str.split('-').str[-1]

# merge to get open and close times for each ticker
kalshi_w_markets = pd.merge(kalshi_df, markets_df_cols, left_on='ticker', right_on='ticker', how='left')

# parse as UTC then convert to Eastern Time
kalshi_w_markets['close_time'] = pd.to_datetime(kalshi_w_markets['close_time'], utc=True).dt.tz_convert('US/Eastern')
kalshi_w_markets['open_time'] = pd.to_datetime(kalshi_w_markets['open_time'], utc=True).dt.tz_convert('US/Eastern')
kalshi_w_markets['timestamp'] = pd.to_datetime(kalshi_w_markets['timestamp'], utc=True).dt.tz_convert('US/Eastern')

# calculate how much time to close
kalshi_w_markets['time_to_close'] = (kalshi_w_markets['close_time'] - kalshi_w_markets['timestamp']).dt.total_seconds()

# rank within each timestamp group so the smallest time_to_close gets rank 1 per timestamp
kalshi_w_markets['close_rank'] = kalshi_w_markets.groupby('timestamp')['time_to_close']\
    .rank(method='dense', ascending=True)

# take only closest ticker
kalshi_w_markets = kalshi_w_markets[kalshi_w_markets['close_rank'] == 1]

In [115]:
### Widen data to have it at timestamp level

# widen 
kalshi_df_wide = kalshi_w_markets.pivot_table(index=["timestamp"], columns="ticker_suffix", values=["volume_fp", "open_dollars", "high_dollars", "low_dollars", "close_dollars", "mean_dollars","open_interest_fp"]).reset_index()

# flatten multiindex columns into single level
kalshi_df_wide.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in kalshi_df_wide.columns
]

# extract weekday and hour from timestamp
kalshi_df_wide['wd'] = kalshi_df_wide['timestamp'].dt.weekday 
kalshi_df_wide['hour'] = kalshi_df_wide['timestamp'].dt.hour

#categorize if markets are asleep
kalshi_df_wide['off_hours'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 3) & (kalshi_df_wide['hour'] >= 17)) # Mon‑Thu after 5pm
| ((kalshi_df_wide['wd'] >= 1) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] < 9)) # Tue‑Fri before 9am
| (kalshi_df_wide['wd'] >= 5) # Sat/Sun all day
| ((kalshi_df_wide['wd'] == 4) & (kalshi_df_wide['hour'] >= 17)) # Fri after 5pm (covers Fri‑Mon weekend block)
| ((kalshi_df_wide['wd'] == 0) & (kalshi_df_wide['hour'] < 9)) # Mon before 9am (end of weekend)
)

#categorize if markets have just closed
kalshi_df_wide['market_close'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] == 17)) # Mon‑Thu after 5pm
# Mon before 9am (end of weekend)
)

#categorize if markets are bout to open
kalshi_df_wide['market_open'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] == 9)) # Mon‑Thu at 9am # Mon before 9am (end of weekend)
)

#categorize if we are in weekend period
kalshi_df_wide['weekend_close_period'] = (
(kalshi_df_wide['wd'] >= 5) # Sat/Sun all day
| ((kalshi_df_wide['wd'] == 4) & (kalshi_df_wide['hour'] >= 17)) # Fri after 5pm (covers Fri‑Mon weekend block)
| ((kalshi_df_wide['wd'] == 0) & (kalshi_df_wide['hour'] < 9)) # Mon before 9am (end of weekend)
)

#get rid of unnecessary column describers
kalshi_df_wide.columns = (
    kalshi_df_wide.columns
    .str.replace('_fp_', '_', regex=False)
    .str.replace('_dollars_', '_', regex=False)
)

In [116]:
# fill in nas with 0 (we are assuming that na corresponds to a paused market hence 0 trading volume 0 price)
kalshi_df_wide = kalshi_df_wide.fillna(0)

# compute an expected rate column based on open interest (total volume across ticker lifetime) of trades per ticker (exclude extreme cuts/hikes)
kalshi_df_wide['exp_rate_open_interest'] = (
    -0.25 * kalshi_df_wide['open_interest_C25']
    + 0 * kalshi_df_wide['open_interest_H0']
    + 0.25 * kalshi_df_wide['open_interest_H25']
) / (
    kalshi_df_wide['open_interest_H0']
    + kalshi_df_wide['open_interest_H25']
    + kalshi_df_wide['open_interest_C25']
)

# compute an expected rate column based on volumes of trades per ticker (exclude extreme cuts/hikes)

kalshi_df_wide['exp_rate'] = (
    -0.25 * kalshi_df_wide['volume_C25']
    + 0 * kalshi_df_wide['volume_H0']
    + 0.25 * kalshi_df_wide['volume_H25']
) / (
    kalshi_df_wide['volume_H0']
    + kalshi_df_wide['volume_H25']
    + kalshi_df_wide['volume_C25']
)

kalshi_df_wide = kalshi_df_wide.fillna(0)

# !!!!!!!! Need to know how will aggregated sp data to merge
# Create a column with relevant date based on timestamp
# - weeknight after 5pm -> same day
# - weeknight before 9am -> previous day
# - weekend (Fri 5pm through Sun) -> following Monday
# - Monday before 9am also counts as Monday

def compute_relevant_date(ts):
    wd = ts.weekday()
    hour = ts.hour

    # weekend closed period assigns next Monday
    if wd == 4 and hour >= 17:  # Fri evening
        return (ts + pd.Timedelta(days=3)).date()
    if wd == 5:  # Saturday
        return (ts + pd.Timedelta(days=2)).date()
    if wd == 6:  # Sunday
        return (ts + pd.Timedelta(days=1)).date()

    # Monday before 9am still considered Monday
    #if wd == 0 and hour < 9:
    #    return ts.date()

    # normal weekday logic
    if hour >= 17:
        return (ts + pd.Timedelta(days=1)).date()
    if hour < 9:
        return ts.date()
    return ts.date()

kalshi_df_wide['relevant_date'] = kalshi_df_wide['timestamp'].apply(compute_relevant_date)

#kalshi_df_wide.to_csv("/Users/marcotaylhardat/Documents/ML/inf_check.csv", index=True)

In [117]:
### Filter to only keep off hours and not weekend close period (we want to see if we can predict overnight price changes based on volume and open interest patterns)
kalshi_df_wide_filtered = kalshi_df_wide[kalshi_df_wide['off_hours']]
kalshi_df_wide_filtered.to_csv("check.csv", index=True)
#kalshi_df_wide_filtered = kalshi_df_wide_filtered[~kalshi_df_wide_filtered['weekend_close_period']]

In [118]:
### Aggregate at overnight level

# Function to calculate % change from first non-zero value to last value in overnight period
def pct_change_start_end(series):
    if len(series) < 2:
        return 0
    
    # Find the first non-zero value
    non_zero_mask = series != 0
    if not non_zero_mask.any():
        return 0  # No non-zero values
    first_non_zero_idx = non_zero_mask.idxmax()  
    start_val = series.loc[first_non_zero_idx]
    end_val = series.iloc[-1]
    if start_val == 0:
        return 0  
    return (end_val - start_val) / start_val

# aggregate
kalshi_grouped_overnight = kalshi_df_wide_filtered.groupby('relevant_date').agg({
    'exp_rate': pct_change_start_end,
    'exp_rate_open_interest': pct_change_start_end,
    'volume_C25': 'sum',
    'volume_H0': 'sum',
    'volume_H25': 'sum',
    'mean_C25': pct_change_start_end,
    'mean_H0': pct_change_start_end,
    'mean_H25': pct_change_start_end,
})

print(kalshi_grouped_overnight.head())
print(kalshi_grouped_overnight['exp_rate_open_interest'].mean())

               exp_rate  exp_rate_open_interest  volume_C25  volume_H0  \
relevant_date
2025-07-31         -1.0                0.102547     20090.0    75482.0
2025-08-01         -1.0               -1.000000     17523.0    36365.0
2025-08-04         -1.0               -1.000000    137586.0   192290.0
2025-08-05         -1.0                0.078286     70086.0    67412.0
2025-08-06         -1.0                0.021213     27087.0    32074.0

               volume_H25  mean_C25  mean_H0  mean_H25
relevant_date
2025-07-31           93.0      -1.0     -1.0      -1.0
2025-08-01         2101.0      -1.0     -1.0      -1.0
2025-08-04        11288.0      -1.0     -1.0      -1.0
2025-08-05          108.0      -1.0     -1.0      -1.0
2025-08-06          100.0      -1.0     -1.0      -1.0
-0.024788073436184086

In [119]:
### Check that number of days seems right
print(kalshi_grouped_overnight.shape)
print(kalshi_grouped_overnight.head())

(162, 8)
               exp_rate  exp_rate_open_interest  volume_C25  volume_H0  \
relevant_date
2025-07-31         -1.0                0.102547     20090.0    75482.0
2025-08-01         -1.0               -1.000000     17523.0    36365.0
2025-08-04         -1.0               -1.000000    137586.0   192290.0
2025-08-05         -1.0                0.078286     70086.0    67412.0
2025-08-06         -1.0                0.021213     27087.0    32074.0

               volume_H25  mean_C25  mean_H0  mean_H25
relevant_date
2025-07-31           93.0      -1.0     -1.0      -1.0
2025-08-01         2101.0      -1.0     -1.0      -1.0
2025-08-04        11288.0      -1.0     -1.0      -1.0
2025-08-05          108.0      -1.0     -1.0      -1.0
2025-08-06          100.0      -1.0     -1.0      -1.0

In [120]:
kalshi_grouped_overnight.info()

<class 'pandas.core.frame.DataFrame'>
Index: 162 entries, 2025-07-31 to 2026-03-12
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   exp_rate                162 non-null    float64
 1   exp_rate_open_interest  162 non-null    float64
 2   volume_C25              162 non-null    float64
 3   volume_H0               162 non-null    float64
 4   volume_H25              162 non-null    float64
 5   mean_C25                162 non-null    float64
 6   mean_H0                 162 non-null    float64
 7   mean_H25                162 non-null    float64
dtypes: float64(8)
memory usage: 11.4+ KB

In [121]:
kalshi_grouped_overnight.head()

,exp_rate,exp_rate_open_interest,volume_C25,volume_H0,volume_H25,mean_C25,mean_H0,mean_H25
relevant_date,,,,,,,,
2025-07-31,-1.0,0.102547,20090.0,75482.0,93.0,-1.0,-1.0,-1.0
2025-08-01,-1.0,-1.000000,17523.0,36365.0,2101.0,-1.0,-1.0,-1.0
2025-08-04,-1.0,-1.000000,137586.0,192290.0,11288.0,-1.0,-1.0,-1.0
2025-08-05,-1.0,0.078286,70086.0,67412.0,108.0,-1.0,-1.0,-1.0
2025-08-06,-1.0,0.021213,27087.0,32074.0,100.0,-1.0,-1.0,-1.0

In [122]:
macrot = pd.read_csv("../data/consolidated_data.csv", index_col = 0)

In [123]:
macrot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 153 entries, 0 to 152
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  153 non-null    object
 1   Close                 153 non-null    float64
 2   High                  153 non-null    float64
 3   Low                   153 non-null    float64
 4   Open                  153 non-null    float64
 5   Volume                153 non-null    int64
 6   Day Change %          153 non-null    float64
 7   Overnight Change %    153 non-null    float64
 8   3m_treasury           153 non-null    float64
 9   2yr_treasury          153 non-null    float64
 10  10yr_treasury         153 non-null    float64
 11  yield_curve           153 non-null    float64
 12  VIX                   153 non-null    float64
 13  fed_funds_rate        153 non-null    float64
 14  Overnight_Return      153 non-null    float64
 15  Overnight_Volatility  153 non-null    float64
 16  Futures_Last_Price    153 non-null    float64
dtypes: float64(15), int64(1), object(1)
memory usage: 21.5+ KB

In [124]:
### Merge with macro data and save final dataset
#kalshi_grouped_overnight.to_csv("/Users/marcotaylhardat/Documents/ML/grouped_overnight_fix.csv", index=True)

# load in macro data
macro_df = pd.read_csv("../data/consolidated_data.csv", index_col = 0)
# convert Date to datetime then extract date to match kalshi format
macro_df['Date'] = pd.to_datetime(macro_df['Date']).dt.date
# reset index to make relevant_date a column, then rename
kalshi_grouped_overnight = kalshi_grouped_overnight.reset_index()
kalshi_grouped_overnight = kalshi_grouped_overnight.rename(columns={"relevant_date": "Date"})

# merge with macro data
kalshi_grouped_overnight = pd.merge(macro_df, kalshi_grouped_overnight, left_on='Date', right_on='Date', how='left')
print(kalshi_grouped_overnight.head())
    
kalshi_grouped_overnight.to_csv("../data/kalshi_w_macro_markets.csv", index=False)

         Date        Close         High          Low         Open      Volume  \
0  2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000
1  2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000
2  2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000
3  2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000
4  2025-08-06  6345.060059  6352.830078  6301.109863  6309.299805  5408560000

   Day Change %  Overnight Change %  3m_treasury  2yr_treasury  ...  \
0     -1.363461            1.007718         4.41          3.94  ...
1     -0.783646           -0.822009         4.35          3.69  ...
2      0.928455            0.540240         4.35          3.69  ...
3     -0.590849            0.105687         4.34          3.72  ...
4      0.566786            0.160495         4.32          3.69  ...

   Overnight_Volatility  Futures_Last_Price  exp_rate  exp_rate_open_interest  \
0              0.002083             6456.75      -1.0                0.102547
1              0.002764             6314.75      -1.0               -1.000000
2              0.000658             6304.00      -1.0               -1.000000
3              0.001891             6365.75      -1.0                0.078286
4              0.001797             6340.25      -1.0                0.021213

   volume_C25  volume_H0  volume_H25  mean_C25  mean_H0  mean_H25
0     20090.0    75482.0        93.0      -1.0     -1.0      -1.0
1     17523.0    36365.0      2101.0      -1.0     -1.0      -1.0
2    137586.0   192290.0     11288.0      -1.0     -1.0      -1.0
3     70086.0    67412.0       108.0      -1.0     -1.0      -1.0
4     27087.0    32074.0       100.0      -1.0     -1.0      -1.0

[5 rows x 25 columns]

In [125]:
kalshi_grouped_overnight.head()

,Date,Close,High,Low,Open,Volume,Day Change %,Overnight Change %,3m_treasury,2yr_treasury,...,Overnight_Volatility,Futures_Last_Price,exp_rate,exp_rate_open_interest,volume_C25,volume_H0,volume_H25,mean_C25,mean_H0,mean_H25
0,2025-07-31,6339.390137,6427.020020,6327.640137,6427.020020,6077080000,-1.363461,1.007718,4.41,3.94,...,0.002083,6456.75,-1.0,0.102547,20090.0,75482.0,93.0,-1.0,-1.0,-1.0
1,2025-08-01,6238.009766,6287.279785,6212.689941,6287.279785,5827150000,-0.783646,-0.822009,4.35,3.69,...,0.002764,6314.75,-1.0,-1.000000,17523.0,36365.0,2101.0,-1.0,-1.0,-1.0
2,2025-08-04,6329.939941,6330.689941,6271.709961,6271.709961,4842580000,0.928455,0.540240,4.35,3.69,...,0.000658,6304.00,-1.0,-1.000000,137586.0,192290.0,11288.0,-1.0,-1.0,-1.0
3,2025-08-05,6299.189941,6346.000000,6289.370117,6336.629883,5517410000,-0.590849,0.105687,4.34,3.72,...,0.001891,6365.75,-1.0,0.078286,70086.0,67412.0,108.0,-1.0,-1.0,-1.0
4,2025-08-06,6345.060059,6352.830078,6301.109863,6309.299805,5408560000,0.566786,0.160495,4.32,3.69,...,0.001797,6340.25,-1.0,0.021213,27087.0,32074.0,100.0,-1.0,-1.0,-1.0